initial release
MadBrains/Gravity-Box-Flutter pull request #1
Opened 2024-10-29 11:25 UTC by kishkihihi

2024-10-31 07:25 UTC, KolasikOmetov requested changes

2024-10-31 07:25 UTC, KolasikOmetov commented on .flutter-plugins
> +gravity_sensor=/Users/nikita/.pub-cache/hosted/pub.dev/gravity_sensor-1.0.1/
не нужно нам знать где у тебя плагин хранится. В гитыгнор его.

2024-10-31 07:25 UTC, KolasikOmetov commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"gravity_sensor","path":"/Users/nikita/.pub-cache/hosted/pub.dev/gravity_sensor-1.0.1/","nativ
Аналогично

2024-10-31 07:25 UTC, KolasikOmetov commented on README.md
> +      ],
А я правильно понимаю, что это стек? И дети этого стека будут за элементами, которые будут от гравитации работать?

Если так, то в чём выгода в отличие от просто обернуть GravityBox в Stack также? Stack(children: [ Positioned(), GravityBox()].
И я бы ещё поработал над названием. Так как это больше похоже на backgroundStaticChildren.

2024-10-31 07:25 UTC, KolasikOmetov commented on example/android/app/build.gradle
> +        applicationId = "ru.madbrains.gravity_box_example"
получается теперь тудушка лишняя

2024-10-31 07:25 UTC, KolasikOmetov commented on example/ios/.gitignore
> +**/dgph
А у тебя плагин разве для ios тоже запускается?

2024-10-31 07:25 UTC, KolasikOmetov commented on lib/gravity_box.dart
> +            child: gravityObjectNotifier.value.widget,
Зачем тут .value.widget, когда ты сможешь без нула и актуальный widget получить из info.

2024-10-31 07:25 UTC, KolasikOmetov commented on lib/src/models/vector.dart
> +class Vector2 with Stringify {
Интересно узнать, чем не подошла эта реализация? https://api.flutter.dev/flutter/vector_math/Vector2-class.html

2024-10-31 07:25 UTC, KolasikOmetov commented on pubspec.yaml
> +publish_to: none
Удали эту строку.
https://education.yandex.ru/handbook/flutter/article/flutter-struktura-proekta#:~:text=%D0%95%D1%81%D0%BB%D0%B8%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%20%D0%BF%D1%83%D1%81%D1%82%D0%BE%D0%B9%2C%20%D1%82%D0%BE%20%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D1%83%D0%B5%D0%BC%D1%8B%D0%B5%20%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D1%8B%20%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%82%D1%81%D1%8F%20%D0%BD%D0%B0%20pub.dev

https://github.com/ivehement/saf/blob/6be3348a496a9251cb4263351797528e65a5f352/pubspec.yaml#L6

2024-10-31 07:25 UTC, KolasikOmetov commented on pubspec.yaml
> +  vector_math: ^2.1.4
Не нашёл где используется.

2024-10-31 08:54 UTC, kishkihihi commented on lib/gravity_box.dart
> +            child: gravityObjectNotifier.value.widget,
потому что это параметр `child`, а `info` передается как аргумент в параметре `build`

2024-10-31 08:54 UTC, kishkihihi commented on example/ios/.gitignore
> +**/dgph
конечно

2024-10-31 08:58 UTC, kishkihihi commented on lib/src/models/vector.dart
> +class Vector2 with Stringify {
Нет константного конструктора

2024-10-31 09:06 UTC, kishkihihi commented on README.md
> +      ],
Да, внутри  стек. Выгода как раз в том, чтобы сразу дать возможность в этот стек добавить виджеты и они будут находится внутри constraints того же стека, что и `GravityObject` и виджеты, подверженные коллизии.
По названию не согласен, `backgroundStaticChildren` тоже так себе, `static` тут ни к чему

2024-11-20 09:55 UTC, KolasikOmetov commented on README.md
> +      ],
А разве constraints не родителями всегда задаётся? То есть  если нужно будет ConstraintBox добавляешь и ограничения общие.

static тут в значении, что не двигаются. А то у тебя всё двигается, но эти дети с гравитацией не связаны - они просто фон.

2024-11-20 10:06 UTC, KolasikOmetov commented on lib/gravity_box.dart
> +            child: gravityObjectNotifier.value.widget,
Я к тому, что по сути в builder: (_, GravityObject info, Widget? child) - GravityObject info является gravityObjectNotifier.value и тебе передавать child не нужно (лишняя проверка на нул). Можно сразу взять info.widget

2024-11-20 10:07 UTC, KolasikOmetov commented on lib/gravity_box.dart
> +            child: gravityObjectNotifier.value.widget,
и контекс нужно вернуть, чтобы всегда был актуальным. (BuildContext context, GravityObject info, _)

2024-11-20 10:33 UTC, kishkihihi commented on README.md
> +      ],
Я считаю, что дать возможность передавать `notCollidableChildren` лучше, чем заставлять всегда оборачивать в еще один `stack`.
Двигается не все, а только `gravityObjects`,  передаваемые `children` и `notCollidableChildren` не обязательно статичны

2024-11-20 10:43 UTC, kishkihihi commented on lib/gravity_box.dart
> +            child: gravityObjectNotifier.value.widget,
`сontext` не используется, поэтому wildcard

2024-11-20 10:52 UTC, KolasikOmetov approved these changes

2024-11-20 10:53 UTC, merged